In [3]:
import numpy as np

In [13]:
a = np.ones((2,2))
print(a)
mask = np.array([[0,0],[1,1]])
    # print(mask[:,0])
a[mask[:,0],mask[:,1]] = 0
print(a)

[[1. 1.]
 [1. 1.]]
[[0. 1.]
 [1. 0.]]


[0 1]
[0 1]
[[0. 1.]
 [1. 0.]]
